### ISSUE TITLE
can not create object from your package

### ISSUE THREAD

**Issue by selenUser** [appium/mitmproxy-java#1]
according to [appiumpro](https://appiumpro.com/editions/65), I imported your project from maven, but because you did not create a package it's using java default package.
That means `private MitmproxyJava proxy;` can not be....

**Comment by dpgraham** [comment]
^ @Jonahss are you able to look at this?

**Comment by Jonahss** [comment]
@selenUser thanks for the help! I put it in a package. releasing right now on maven as version 1.6.2. When maven makes it available can you try again?

**Comment by selenUser** [comment]
@Jonahss sure i will try
how can i know when it ready ?

**Comment by Jonahss** [comment]
@selenUser it should be available now. Maven central is very ambiguous. I have had to wait 30 min before the a library I "released" to actually be downloaded by my gradle sync. I think it just takes a while to propagate through the system and get put onto the CDNs or whatever.

**Comment by selenUser** [comment]
it fixed, thanks

**Comment by Jonahss** [comment]
@selenUser create more issues if you run into problems or want features!

**Comment by selenUser** [comment]
@Jonahss i'm starting to try your project, i will let you know !

**Comment by selenUser** [comment]
@Jonahss where can i found mitmproxy-ca-cert.pem file ?
i'm trying to automate install certificate on android real device and your example is not full.
thanks for your help

**Comment by selenUser** [comment]
founded mitmproxy-ca-cert.pem file !

**Comment by Jonahss** [comment]
Ah yeah, the setup for that part was in an earlier article for the initial set up. is there a more convenient place I could mention it? maybe in the readme for this project...
