### ISSUE TITLE
can not install certificate

### ISSUE THREAD

**Issue by selenUser** [appium/mitmproxy-java#2]
running your code
`Path certificatePath = Paths.get(System.getProperty("user.home"), ".mitmproxy", "mitmproxy-ca-cert.pem");
			Map<String, Object> args = new HashMap<>();
			byte[] byteContent = Files.readAllBytes(certificatePath);
			args.put("content", Base64.getEncoder().encodeToString(byteContent));
			androidDriver.executeScript("mobile: installCertificate", args);`

and getting appium error to install cretificate [click for log](https://gist.github.com/selenUser/c254ea85eba7c09fdab60100b71304ba)

**Comment by selenUser** [comment]
@Jonahss

**Comment by Jonahss** [comment]
`mobile:installCertificate` only works on iOS. For android, you can either do it manually or with a couple shell commands, described in this post: https://appiumpro.com/editions/63

**Comment by Jonahss** [comment]
does that solve it?

**Comment by selenUser** [comment]
yes, but the code does not catch traffic....
can you please help me ?

**Comment by Jonahss** [comment]
sure! did you configure the android emulator to use the proxy?
I suggest starting the entire process manually, running mitmproxy in a terminal, setting up an emulator, making sure you can capture traffic. once that works, it will be easier to diagnose problems with using the library.

have yo already confirmed it working at this step?
