### ISSUE TITLE
Maven, MitmProxy version 9: AttributeError: module 'mitmproxy.http' has no attribute 'HTTPResponse'

### ISSUE THREAD

**Issue by bp32891** [appium/mitmproxy-java#20]
Hello,

I recently started a Maven project using mitmproxy-java. Anytime I try to change the status code of an intercepted call, I get this error: AttributeError: module 'mitmproxy.http' has no attribute 'HTTPResponse'

`List<InterceptedMessage> messages = new ArrayList<>();

        MitmproxyJava proxy = new MitmproxyJava("/Library/Frameworks/Python.framework/Versions/3.10/bin/mitmdump", (InterceptedMessage m) -> {
            messages.add(m);
            m.getResponse().setBody("Hi from Test".getBytes(StandardCharsets.UTF_8));
            m.getResponse().getHeaders().add(new String[]{"myTestResponseHeader", "myTestResponseHeaderValue"});
            m.getResponse().setStatusCode(500);
            return m;
        });
        proxy.start();

        Unirest.setProxy(new HttpHost("localhost", 8080));
        HttpResponse<String> response = Unirest.get("http://appium.io").asString();

        driver.get("http://appium.io");

        System.out.println("RESPONSE");
        System.out.println(messages.get(0));

        TimeUnit.SECONDS.sleep(15);

        proxy.stop();

        assertThat(response.getBody()).isEqualTo("Hi from Test");

        final InterceptedMessage firstMessage = messages.get(0);

        assertThat(firstMessage.getRequest().getUrl()).startsWith("http://appium.io/");
        assertThat(firstMessage.getRequest().getHeaders()).containsOnlyOnce(new String[]{"myTestHeader", "myTestValue"});
        assertThat(firstMessage.getResponse().getHeaders()).containsOnlyOnce(new String[]{"myTestResponseHeader", "myTestResponseHeaderValue"});
        System.out.println(firstMessage.getResponse().getStatusCode());
        assertThat(firstMessage.getResponse().getStatusCode()).isEqualTo(500);`

I see that the newest version is 2.0.2 and I'm hoping it has the fix. But currently only 2.0.1 is available on Maven to insert into the POM file.

**Comment by t-o-n-y-p** [comment]
Hello, same thing here. Could you please push the fix to maven central? Thanks.

**Comment by shlmvgett** [comment]
Hi
The same problem is actual for us, could u update version on mvn repo?

**Comment by bp32891** [comment]
I did find a work around until they make a push. I created my on jar file from this repo and added it to my pom. Then I had to add more libraries but it now works. I no longer get the error message.

**Comment by Jonahss** [comment]
Sorry about the delay. I'll see about updating in Maven.

**Comment by Jonahss** [comment]
Hi, I've been busy on my [Wyldcard](https://www.wyldcard.io/blog/introducing-wyldcard) project, but thanks for poking me to update this. I'll see if I can do it on Monday.

**Comment by jlipps** [comment]
that's such a cool project dude!

**Comment by Jonahss** [comment]
I'm finally working on it :D
My credentials to Maven Central are no longer valid. I'm talking to the active Appium team to get access.

Thanks for pinging me, sorry for the delay.

**Comment by t-o-n-y-p** [comment]
Hello, how is the progress on this?

**Comment by Jonahss** [comment]
Hello. I think I have everything I need now. Will work on this today and tomorrow. Thanks again for pinging.

**Comment by Jonahss** [comment]
@t-o-n-y-p @re-jim v2.0.2 published to central repository.
Can you verify the code works as intended?

**Comment by t-o-n-y-p** [comment]
Unfortunately, I no longer have access to the environment to check it, thanks for publishing though :)

**Comment by Jonahss** [comment]
Ah, well, hopefully someone else can check. Or we'll hear about it here
when it fails to work XD

**Comment by halilcifteci** [comment]
Hi, after upgrading my project, there was no problem. thanks @Jonahss

**Comment by Jonahss** [comment]
Yay! Okay, can close with confidence :D
