### ISSUE TITLE
No module named 'websockets'

### ISSUE THREAD

**Issue by adamMo** [appium/mitmproxy-java#5]
[Win10]
Hello, I tried to run the library, it keeps telling me that: 

> 22:45:33.231 [Thread-6] INFO io.appium.mitmproxy.MitmproxyJava - Loading script C:\Users\Adam\AppData\Local\Temp\mitmproxy-python-plugin5399613169945565656.py
> 22:45:33.231 [Thread-6] INFO io.appium.mitmproxy.MitmproxyJava - in script C:\Users\Adam\AppData\Local\Temp\mitmproxy-python-plugin5399613169945565656.py: No module named 'websockets'
> 22:45:33.232 [Thread-6] INFO io.appium.mitmproxy.MitmproxyJava - Proxy server listening at http://*:8080

I used pip3 to install websockets module but it looks like the script is somehow not using it, so at the end the handler function is not called. Do you have any idea what's going on?

**Comment by Jonahss** [comment]
I think I know what’s going on, how did you install mitmproxy itself? You
have to install it via pip or from source, homebrew or the prebuilt
binaries won’t work.

**Comment by adamMo** [comment]
So I installed it by chocolatey package manager, it qualifies to be the prebuilt binaries? :)

**Comment by Jonahss** [comment]
Ah yeah, that’s the issue. The version of mitmproxy that comes from your
package manager has it’s own version of Python which cannot interact with
the modules you download.

Since you have chocolatey, you can install python and pip. Then use pip to
install mitmproxy and you should be good to go.
Don’t forget to uninstall mitmproxy using chocolatey first, so things don’t
get confused.

**Comment by adamMo** [comment]
Ok, I did all of this and it works ok but I see the difference when comparing to standalone version... I ran selenium with proxy and I can intercept the requests which is cool but when trying to log in to youtube account, google says that my browser has no cookies enabled. When I tried to do this on 'pure' mitmproxy it was working good, do you have any idea what could go wrong?

**Comment by Jonahss** [comment]
Ok that’s interesting. When ypu say “pure mitmproxy” you mean using it
alone from the commandline, not with java, right?

Something about the python plugin must be messing up cookies. I can take a
look but am currently traveling to speak at Mobile Test Summit China 2019.
I can look into this once I get back from China in a few days.

Unless you are able to take a look at the puthon code and try debugging?

**Comment by adamMo** [comment]
> Ok that’s interesting. When ypu say “pure mitmproxy” you mean using it
alone from the commandline, not with java, right?

Right :)

I am not a python expert but I will try to debug what's going on.

Have a nice time!
